export const pathNames = {
  DASHBOARD: '/',
  LOGIN: '/login',
  LOGOUT: '/logout',
  REGISTER: '/register',
  TWOFA: '/TwoFa',
  ACCOUNTCREATEDPAGE: '/account_created',
  ONBOARDING: '/onboarding',
  MAINTENANCE_PAGE: '/maintenance-page',
  ISSUANCE_DATA_COLLECTION: '/issuance-data-collection',
  ISSUANCE_DATA_COLLECTION_HELP: '/issuance-data-collection/help',
  PROFILE_DETAILS_ISSUANCE_INFO: '/profile-details-issuance-info',
  MARKETPLACE: '/marketplace',
  MARKETPLACE_PROJECT_DETAILS: '/marketplace-project-details',
  PROJECTS: '/projects',
  PROJECTS_LIST: '/projects-list',
  LIST_NEW_PROJECT: '/list-new-project',
  SELECT_VERIFIER: '/select-verifier',
  SEE_ALL_PROJECTS: '/see-all-projects',
  TOKEN_CONTRACT: '/token-contract',
  VERIFIER_DASHBOARD: '/verifier-dashboard',
  VERIFIER_PROFILE_SETUP: '/verifier-profile-setup',
  VERIFIER_PROJECTS: 'verifier-projects',
  MONTHLY_REPORT_UPDATE: '/monthly-report-update',
  VERIFIER_PROJECTS_LIST: '/verifier-projects-list',
  VERIFIER_PROJECTS_DETAILS: '/verifier-projects-details',
  VERIFIER_VERIFY_REPORT: '/verifier-verify-report',
  ISSUER_WALLET: '/issuer-wallet',
  TRANSACTION_HISTORY: '/transaction-history',
  BANK_DETAILS: '/bank-details',
  REPORT_VIEW_COMMENTS: '/report-view-comments',
  BUYER_ONBOARDING: '/buyer-onboarding',
  ORGANISATIONAL_DETAILS: '/organisational-details',
  RETIRE_TOKENS: '/retire-tokens',
  TOKENS_RETIREMENT: '/token-retirement',
  RESET_PASSWORD: '/reset-password',
  PROFILE: '/profile',
  HELP_CENTER: '/help-center',
  PROJECT_DETAILS: '/project-details',
  PROJECT_DETAILS_REGISTRY_ACC: '/project-details-registry-acc',
  PROJECT_LISTS_WITH_FILTER: '/project-lists-with-filter',
  REGISTRY_REVIEW_REPORT: '/registry-review-report',
}

export const linkLabels = {
  Dashboard: 'Dashboard',
  Token_Contract: 'Tokens & Reports',
  // My_Portfolio: 'My Portfolio',
  Marketplace: 'Marketplace',
  Wallet: 'Wallet',
  TokenRetirement: 'Token Retirement',
  Projects: 'Projects',
}
