export const headings = [
  'Registration No.',
  'Title',
  'Project Type',
  'Country',
  'Report',
  'Methodology',
  'Standard',
  'Status',
]

export const data = [
  {
    title: 'BK Energia Itacoatiara Project',
    projectType: 'Energy industries (renewable - / non-renewable sources)',
    country: 'Brazil',
    methodology: 'AMS-I.D. ver. 6 AMS-III.E. ver. 6',
    standard: 'CDM',
    status: 'Registered',
    ref: '0168',
    pdfLoc: require('../../assets/helpPagePDFs/bk-energia.pdf'),
  },
  {
    title:
      'Catalytic N2O destruction project in the tail gas of the nitric acid plant PANNA 3 of Enaex S.A.',
    projectType: 'Chemical industries',
    country: 'Chile',
    methodology: 'AM0028 ver. 4',
    standard: 'CDM',
    status: 'Registered',
    ref: '1229',
    pdfLoc: require('../../assets/helpPagePDFs/catalytic-n2o.pdf'),
  },
  {
    title: 'Assisted Natural Regeneration of Degraded Lands in Albania',
    projectType: 'Afforestation and reforestation',
    country: ' Albania ',
    methodology: 'AR-AM0003 ver. 4',
    standard: 'CDM',
    status: 'Registered',
    ref: '2714',
    pdfLoc: require('../../assets/helpPagePDFs/assisted-natural.pdf'),
  },
  {
    title: 'Trueno River Hydroelectric Power Plant',
    projectType: 'Energy industries (renewable - / non-renewable sources)',
    country: 'Brazil',
    methodology: 'AMS-I.D. ver. 15',
    standard: 'CDM',
    status: 'Registered',
    ref: '4337',
    pdfLoc: require('../../assets/helpPagePDFs/trueno-river.pdf'),
  },
  // {
  //   title: '',
  //   projectType: '',
  //   country: '',
  //   methodology: '',
  //   standard: 'CDM',
  //   status: 'Registered',
  //   ref: ' ',
  // },
]

export const projectTypes = [
  'Agriculture',
  'Chemical industries',
  'Construction',
  'Energy distribution',
  'Energy demand',
  'Energy industries (renewable - / non-renewable sources)',
  'Fugitive emissions from fuels (solid, oil and gas)',
  'Fugitive emissions from production and consumption of halocarbons and sulphur hexafluoride',
  'Livestock, enteric fermentation, and manure management',
  'Manufacturing industries',
  'Metal production',
  'Mining/mineral production',
  'Solvent use',
  'Transport',
  'Waste handling and disposal',
  'Afforestation and reforestation',
  'Forestry and Other Land Use',
  'Forest conservation (REDD+)',
  'Blue carbon',
]
