# Default values for  application in dev environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment:
  name: dev

replicaCount: 1

image:
  repository: registry.gitlab.com/shine-traceability/front-end/nse-gold-webapp

service:
  type: ClusterIP
  port: 80

containers:
  port: 80

environmentVariables: {}

podAntiAffinity:
  enabled: true
