# Default values for application in prod environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment:
  name: production

replicaCount: 1

image:
  repository: registry.gitlab.com/shinex-tech/carbon-credit/carbon-credit-webapp

service:
  type: NodePort
  port: 80

containers:
  port: 80

environmentVariables: {}

podAntiAffinity:
  enabled: true
