# Default values for  application in staging environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment:
  name: staging

replicaCount: 1

image:
  repository: registry.gitlab.com/shinex-tech/carbon-credit/carbon-credit-webapp

service:
  type: ClusterIP
  port: 80

containers:
  port: 80

environmentVariables: {}

podAntiAffinity:
  enabled: true
